version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo nothing to do here
  pre_build:
    commands:
      - echo nothing to do here
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'target/democicd.war'
    - 'appspec.yml'
    - 'scripts/*.*'